- name: Discover vCenter inventory
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get datacenters
      community.vmware.vmware_datacenter_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_password }}"
        validate_certs: false
      register: dc

    - name: Get clusters
      community.vmware.vmware_cluster_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_password }}"
        validate_certs: false
      register: cluster

    - name: Show results
      debug:
        msg:
          - "Datacenters: {{ dc.datacenter_info | map(attribute='name') | list }}"
          - "Clusters: {{ cluster.clusters | map(attribute='cluster_name') | list }}"
          
