---
- name: Setup Passwordless SSH Between All VMs
  hosts: all
  become: false
  vars:
    ssh_user: itadmin
    ssh_key_file: /home/itadmin/.ssh/id_rsa

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ ssh_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Generate SSH key using ssh-keygen if not exists
      shell: |
        if [ ! -f "{{ ssh_key_file }}" ]; then
          sudo -u {{ ssh_user }} ssh-keygen -t rsa -b 2048 -f "{{ ssh_key_file }}" -N ""
        fi
      args:
        creates: "{{ ssh_key_file }}"

    - name: Fetch public key from remote server
      fetch:
        src: "{{ ssh_key_file }}.pub"
        dest: "/tmp/{{ inventory_hostname }}_id_rsa.pub"
        flat: yes
      delegate_to: localhost

    - name: Set fact with public key content
      set_fact:
        all_pub_keys: "{{ lookup('file', '/tmp/' + inventory_hostname + '_id_rsa.pub') }}"

    - name: Add public key to authorized_keys
      authorized_key:
        user: "{{ ssh_user }}"
        key: "{{ all_pub_keys }}"
        state: present
      loop: "{{ groups['all'] }}"
      delegate_to: "{{ item }}"
