---
- name: Install Application Server and deploy Django backend
  hosts: app-server-01
  become: yes
  vars:
    app_directory: "/opt/myapp"
    venv_directory: "{{ app_directory }}/venv"
    django_project_name: "myproject"

  tasks:
    - name: Install required packages for Python (Django) and virtualenv
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-dev
          - python3-django
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0755'

    - name: Check if virtual environment exists
      stat:
        path: "{{ venv_directory }}"
      register: venv_stat

    - name: Create virtual environment
      command: python3 -m venv {{ venv_directory }}
      when: not venv_stat.stat.exists

    - name: Install Django in virtual environment
      pip:
        name: django
        virtualenv: "{{ venv_directory }}"
      become_user: itadmin

    - name: Create Django project (only if not exists)
      command: django-admin startproject {{ django_project_name }}
      args:
        chdir: "{{ app_directory }}"
      when: not (ansible_facts['ansible_mounts'] | selectattr('mount', 'equalto', app_directory) | map(attribute='mount') | list)[0]

    - name: Update Django settings to allow all hosts
      lineinfile:
        path: "{{ app_directory }}/{{ django_project_name }}/{{ django_project_name }}/settings.py"
        regexp: "^ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"
        owner: itadmin
        group: itadmin
        mode: '0644'

    - name: Create a systemd service for Django app
      copy:
        dest: /etc/systemd/system/django-app.service
        content: |
          [Unit]
          Description=Django Application
          After=network.target

          [Service]
          WorkingDirectory={{ app_directory }}/{{ django_project_name }}
          ExecStart={{ venv_directory }}/bin/python3 {{ app_directory }}/{{ django_project_name }}/manage.py runserver 0.0.0.0:8000
          Restart=always
          User=itadmin

          [Install]
          WantedBy=multi-user.target

    - name: Set correct permissions on systemd service file
      file:
        path: /etc/systemd/system/django-app.service
        mode: '0644'

    - name: Start Django application service
      systemd:
        name: django-app
        state: started
        enabled: yes
