---
- name: Install Application Server and deploy Django backend
  hosts: app-server-01
  become: yes
  vars:
    app_directory: "{{ app_directory }}"
    venv_directory: "{{ venv_directory }}"
    django_project_name: "myproject"

  tasks:
    - name: Install required packages for Python (Django) and virtualenv
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-dev
          - python3-django
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0755'

    - name: Create Django project
      command: django-admin startproject {{ django_project_name }}
      args:
        chdir: "{{ app_directory }}"

    - name: Update Django settings to allow all hosts
      lineinfile:
        path: "{{ app_directory }}/{{ django_project_name }}/{{ django_project_name }}/settings.py"
        regexp: "^ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"
        owner: itadmin
        group: itadmin
        mode: '0644'

    - name: Start Django development server (run in the background)
      command: python3 {{ app_directory }}/{{ django_project_name }}/manage.py runserver 0.0.0.0:8000
      args:
        chdir: "{{ app_directory }}/{{ django_project_name }}"
      async: 600
      poll: 0
