---
- name: Install Application Server and deploy backend
  hosts: app-server-01
  become: yes
  vars:
    app_directory: "/opt/myapp"
    venv_directory: "{{ app_directory }}/venv"
    project_directory: "{{ app_directory }}/myproject"

  tasks:
    - name: Install required packages for Python (Django)
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-django
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0755'

    - name: Create virtual environment
      command: python3 -m venv {{ venv_directory }}
      creates: "{{ venv_directory }}"

    - name: Activate virtual environment and install Django
      pip:
        name: django
        virtualenv: "{{ venv_directory }}"
      become_user: itadmin

    - name: Check if Django project already exists
      stat:
        path: "{{ project_directory }}"
      register: project_exists

    - name: Create Django project if it doesn't exist
      command: django-admin startproject myproject
      args:
        chdir: "{{ app_directory }}"
      when: not project_exists.stat.exists

    - name: Start the Django app
      command: "{{ venv_directory }}/bin/python3 {{ project_directory }}/manage.py runserver 0.0.0.0:8000"
      args:
        chdir: "{{ app_directory }}"
      async: 0
      poll: 0
