---
- name: Install OpenSSH Server and start SSH service
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Install OpenSSH server
      apt:
        name: openssh-server
        state: present
        update_cache: yes
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Ensure SSH service is started
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Allow SSH through UFW firewall
      ufw:
        rule: allow
        name: ssh
        state: enabled
        enabled: yes
      when: ansible_facts['distribution'] == 'Ubuntu'
