- name: Set up SSH Key-based Authentication on VMs
  hosts: 
    - web
    - app
    - db
  become: true
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/itadmin/.ssh
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0700'

    - name: Generate SSH key if not exists
      command:
        cmd: "ssh-keygen -t rsa -b 2048 -f /home/itadmin/.ssh/id_rsa -N ''"
        creates: "/home/itadmin/.ssh/id_rsa"
        
    - name: Collect public key
      slurp:
        src: /home/itadmin/.ssh/id_rsa.pub
      register: pubkey

    - name: Share public keys among all VMs
      authorized_key:
        user: itadmin
        key: "{{ hostvars[item].pubkey.content | b64decode }}"
      loop: "{{ groups['all'] }}"
