- name: Set up SSH Key-based Authentication on VMs
  hosts: localhost
  become: false
  gather_facts: yes
  vars:
    ssh_key_path: /root/.ssh/id_rsa  # Use /root/.ssh or another directory you have access to

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ssh_key_path | dirname }}"  # Ensure the directory exists
        state: directory
        mode: '0700'

    - name: Generate SSH key if not exists
      command:
        cmd: "ssh-keygen -t rsa -b 2048 -f {{ ssh_key_path }} -N ''"
        creates: "{{ ssh_key_path }}"

    - name: Read public key
      slurp:
        src: "{{ ssh_key_path }}.pub"
      register: pubkey

    - name: Add public key to authorized_keys on all VMs
      authorized_key:
        user: itadmin
        key: "{{ pubkey.content | b64decode }}"
        state: present
      loop: "{{ vm_ips }}"
      loop_control:
        loop_var: ip_data
      delegate_to: "{{ ip_data.ip }}"
