- name: Set up SSH Key-based Authentication on VMs
  hosts: localhost  # Localhost because we are passing IPs dynamically
  become: true
  vars:
    ssh_key_path: /home/itadmin/.ssh/id_rsa

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/itadmin/.ssh
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0700'

    - name: Generate SSH key if not exists
      command:
        cmd: "ssh-keygen -t rsa -b 2048 -f {{ ssh_key_path }} -N ''"
        creates: "{{ ssh_key_path }}"

    - name: Read public key
      slurp:
        src: "{{ ssh_key_path }}.pub"
      register: pubkey

    - name: Add public key to authorized_keys on all VMs
      authorized_key:
        user: itadmin
        key: "{{ pubkey.content | b64decode }}"
        state: present
      loop: "{{ vm_ips }}"  # Loop through the dictionary
      loop_control:
        loop_var: ip_data
      delegate_to: "{{ ip_data.ip }}"  # Delegate the task to each specific IP
      vars:
        node_role: "{{ ip_data.role }}"
        node_ip: "{{ ip_data.ip }}"
