- name: Setup SSH Key-based Access on All VMs
  hosts: all
  become: true
  vars:
    ssh_key_path: /home/itadmin/.ssh/id_rsa

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/itadmin/.ssh
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0700'

    - name: Generate SSH key if not exists
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}"
        owner: itadmin
        group: itadmin
        mode: '0600'
        type: rsa
        size: 2048

    - name: Read public key
      ansible.builtin.slurp:
        src: "{{ ssh_key_path }}.pub"
      register: pubkey

    - name: Share SSH keys among all nodes
      ansible.posix.authorized_key:
        user: itadmin
        key: "{{ hostvars[item].node_pubkey }}"
      loop: "{{ groups['all'] }}"
      loop_control:
        loop_var: item
      vars:
        node_pubkey: "{{ pubkey.content | b64decode }}"
