- name: Setup SSH Key-Based Authentication Between VMs
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/itadmin/.ssh
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0700'

    - name: Generate SSH key if not exists
      openssh_keypair:
        path: /home/itadmin/.ssh/id_rsa
        owner: itadmin
        group: itadmin
        mode: '0600'
        type: rsa
        size: 2048

    - name: Collect public key
      slurp:
        src: /home/itadmin/.ssh/id_rsa.pub
      register: pubkey

    - name: Share public keys among all VMs
      authorized_key:
        user: itadmin
        key: "{{ hostvars[item].pubkey.content | b64decode }}"
      loop: "{{ groups['all'] }}"
