- name: Set up SSH Key-based Authentication on VMs
  hosts: all  # This targets all the hosts in your inventory
  become: true
  vars:
    ssh_key_path: /home/itadmin/.ssh/id_rsa

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/itadmin/.ssh
        state: directory
        owner: itadmin
        group: itadmin
        mode: '0700'

    - name: Generate SSH key if not exists
      command:
        cmd: "ssh-keygen -t rsa -b 2048 -f {{ ssh_key_path }} -N ''"
        creates: "{{ ssh_key_path }}"
        
    - name: Read public key
      slurp:
        src: "{{ ssh_key_path }}.pub"
      register: pubkey

    - name: Add all public keys to authorized_keys
      authorized_key:
        user: itadmin
        key: "{{ hostvars[item].node_pubkey }}"
      loop: "{{ groups['web'] + groups['app'] + groups['db'] }}"  # Loop through each group individually
      loop_control:
        loop_var: item
      vars:
        node_pubkey: "{{ pubkey.content | b64decode }}"
