---
- name: Install SSH and set up passwordless SSH using password authentication
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Install OpenSSH Server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Ensure SSH service is started and enabled
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Ensure password authentication is enabled in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: Restart SSH

    - name: Ensure SSH service is restarted after changing configuration
      service:
        name: ssh
        state: restarted
      when: ansible_facts['distribution'] == 'Ubuntu'

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
